services:
  api:
#    build: .
    image: quarkus/finance-api-jvm:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:14-alpine # You can choose a specific version like 14-alpine
    restart: always
    environment:
      POSTGRES_USER: admin_username # Replace with your desired username
      POSTGRES_PASSWORD: admin_password # Replace with a strong password
      POSTGRES_DB: finance # Replace with your desired database name
    ports:
      - "5431:5432" # Maps host port 5432 to container port 5432
    volumes:
      - db_data:/var/lib/postgresql/data # Persists data to a named volume

volumes:
  db_data: # Defines the named volume for data persistence